server:
  port: 8000
  servlet:
    context-path: /api/v1
spring:
  application:
    name: eks-order
  profiles:
    active: prod

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: false

